services:
  backend:
    build:
      context: ./src/backend/jcf.anasstore
      dockerfile: Dockerfile
    container_name: anasstore-backend
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS?Defina ASPNETCORE_URLS no .env}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT?Defina ASPNETCORE_ENVIRONMENT no .env}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION?Defina DB_CONNECTION no .env}
      JwtSettings__SigningKey: ${JwtSettings__SigningKey?Defina JwtSettings__SigningKey no .env}
      JwtSettings__Issuer: ${JwtSettings__Issuer?Defina JwtSettings__Issuer no .env}
      JwtSettings__Audience: ${JwtSettings__Audience?Defina JwtSettings__Audience no .env}
      JwtSettings__ExpirationMinutes: ${JwtSettings__ExpirationMinutes?Defina JwtSettings__ExpirationMinutes no .env}
      Database__AutoMigrate: ${Database__AutoMigrate?Defina Database__AutoMigrate no .env}
      Seed__EnableLookupSeed: ${Seed__EnableLookupSeed?Defina Seed__EnableLookupSeed no .env}
      Seed__EnableDefaultUsers: ${Seed__EnableDefaultUsers?Defina Seed__EnableDefaultUsers no .env}
    ports:
      - "5117:8080"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: anasstore-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL?Defina VITE_API_BASE_URL no .env}
    ports:
      - "5173:80"

