namespace Jcf.AnasStore.Api.Contracts.Organization;

public sealed record OrganizationResponse(
    Guid Uid,
    string LegalName,
    string TradeName,
    string? Cnpj,
    string Phone,
    string Email,
    DateOnly? OpeningDate,
    string? Cnae,
    string? StateRegistration,
    string Administrator,
    long AddressId,
    Guid AddressUid,
    string? Place,
    string? Number,
    string? Neighborhood,
    string? Complement,
    string? ZipCode,
    string? City,
    string? State,
    bool IsActive,
    DateTime CreateAt,
    DateTime? UpdateAt);
